services:
  mongo:
    image: mongo:7.0
    container_name: bounded-mart-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: bounded-mart

    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: bounded-mart-mongo-express
    restart: unless-stopped

    depends_on:
      - mongo

    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"

  api:
    image: bounded-mart-api
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bounded-mart
    restart: unless-stopped

    depends_on:
      - mongo

    ports:
      - "${API_PORT:-3000}:3000"

    environment:
      API_PORT: ${API_PORT:-3000}
      MONGO_URI: mongodb://mongo:27017/bounded-mart

    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

volumes:
  mongo_data:
